{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-flow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flow/flow_{{ version }}.tar.gz
  sha256: e9d3866b4f5520418e97d996e12695b775dcfb81a9c07b20ecb410726fd32c9c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-here
    - r-htmlwidgets
    - r-lifecycle
    - r-nomnoml
    - r-rstudioapi
    - r-styler
    - r-webshot
  run:
    - r-base
    - r-here
    - r-htmlwidgets
    - r-lifecycle
    - r-nomnoml
    - r-rstudioapi
    - r-styler
    - r-webshot

test:
  commands:
    - $R -e "library('flow')"           # [not win]
    - "\"%R%\" -e \"library('flow')\""  # [win]

about:
  home: https://moodymudskipper.github.io/flow/
  dev_url: https://github.com/moodymudskipper/flow
  license: MIT
  summary: Visualize as flow diagrams the logic of functions, expressions or scripts in a static
    way or when running a call, visualize the dependencies between functions or between
    modules in a shiny app, and more.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: flow
# Title: View and Browse Code Using Flow Diagrams
# Version: 0.2.0
# Authors@R: person(given = "Antoine", family = "Fabri", role = c("aut", "cre"), email = "antoine.fabri@gmail.com")
# Description: Visualize as flow diagrams the logic of functions, expressions or scripts in a static way or when running a call, visualize the dependencies between functions or between modules in a shiny app, and more.
# License: MIT + file LICENSE
# URL: https://github.com/moodymudskipper/flow, https://moodymudskipper.github.io/flow/
# BugReports: https://github.com/moodymudskipper/flow/issues
# Encoding: UTF-8
# Imports: nomnoml, utils, htmlwidgets, rstudioapi, webshot, styler, methods, here, lifecycle
# Suggests: testthat (>= 3.0.0), covr, knitr, rmarkdown, esquisse, tidyselect, purrr
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-06-06 11:47:40 UTC; Antoine
# Author: Antoine Fabri [aut, cre]
# Maintainer: Antoine Fabri <antoine.fabri@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-06-06 12:40:02 UTC
